import type { ScannedServerRoute } from './scan'
import {
  CALLA_META_NAME,
  clearCallaMetaFieldCache,
  getExportedCallaMetaFields,
} from './calla-meta'

export const CALLA_MODULE_ID = '#calla/calla'

type ScannedHandler = ScannedServerRoute

interface PayloadSchema {
  body?: string
  query?: string
  res?: string
}

interface RouteSchema {
  default?: PayloadSchema
  [method: string]: PayloadSchema | undefined
}

type PayloadMap = Record<string, RouteSchema>

function getRouteTargets(
  routeSchema: RouteSchema,
  method?: string,
): PayloadSchema[] {
  const targets: PayloadSchema[] = []

  if (!method || method.toUpperCase() === 'GET') {
    routeSchema.default ??= {}
    targets.push(routeSchema.default)
  }

  if (method) {
    const methodKey = method.toLowerCase()
    routeSchema[methodKey] ??= {}
    targets.push(routeSchema[methodKey]!)
  }

  return targets
}

function generatePayloadCode(payloadMap: PayloadMap) {
  return Object.entries(payloadMap)
    .map(([route, methods]) => {
      const methodsCode = Object.entries(methods)
        .map(([method, schema]) => {
          if (!schema) return ''

          const props: string[] = []
          if (schema.body) props.push(`body: ${schema.body}`)
          if (schema.query) props.push(`query: ${schema.query}`)
          if (schema.res) props.push(`res: ${schema.res}`)

          return [
            `      ${method}: {`,
            ...props.map(prop => `        ${prop},`),
            '      }',
          ].join('\n')
        })
        .filter(Boolean)
        .join('\n')

      return `    '${route}': {\n${methodsCode}\n    }`
    })
    .join('\n')
}

async function buildPayloadMap(handlers: ScannedHandler[]) {
  clearCallaMetaFieldCache()

  const payloadMap: PayloadMap = {}

  await Promise.all(
    handlers.map(async ({ handler: filePath, method, route }) => {
      const metaFields = await getExportedCallaMetaFields(filePath)
      if (!metaFields.length) {
        return
      }

      const importPath = filePath.replace(/\.[a-z]+$/, '')
      payloadMap[route] ??= {}

      const typeRef = `import('${importPath}').${CALLA_META_NAME}`
      const targets = getRouteTargets(payloadMap[route], method)

      for (const target of targets) {
        metaFields.forEach((field) => {
          target[field] = `${typeRef}['${field}']`
        })
      }
    }),
  )

  return payloadMap
}

export async function genCallaTemplate(
  handlers: ScannedHandler[],
  injectCallaToGlobal: boolean,
): Promise<string> {
  const payloadMap = await buildPayloadMap(handlers)
  const payloadCode = generatePayloadCode(payloadMap)

  const lines = [
    '// Generated by calla module. Do not edit manually.',
    `declare module '${CALLA_MODULE_ID}' {`,
    '  interface InternalApiPayload {',
    payloadCode,
    '  }',
    '}',
  ]

  if (injectCallaToGlobal) {
    lines.push(
      '',
      'declare global {',
      `  var calla: typeof import('${CALLA_MODULE_ID}').calla`,
      '}',
    )
  }

  lines.push('', 'export {}')

  return lines.join('\n')
}
